drop table if exists accounts;

create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15, 2) not null,
    place_id int not null,
    transportation varchar(100),
    gender varchar(100) not null,
    primary key(id)
);

insert into accounts(name, balance, place_id,transportation,gender)
values('agus', 10000, 1, 'kereta','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('budi', 10300, 2, 'kereta api','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('andi', 1000, 3, 'kereta listrik','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('asep', 80000, 3, 'mobil','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('rudi', 108000, 4, 'kereta kencana','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('gusti', 70000, 5, 'kereta kuda','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('asri', 80000, 3, 'mobil','female');

insert into accounts(name, balance, place_id,transportation,gender)
values('diyah', 108000, 4, 'kereta kencana','female');

insert into accounts(name, balance, place_id,transportation,gender)
values('asha', 70000, 5, 'kereta kuda','female');

insert into accounts(name, balance, place_id,transportation,gender)
values('gema', 11800, 9, 'kereta kuda','male');

insert into accounts(name, balance, place_id,transportation,gender)
values('gema', 12800, 10, 'kereta','female');

insert into accounts(name, balance, place_id,transportation,gender)
values('dimas', 10000, 30, NULL,'male');

insert into accounts(name, balance, place_id,transportation,gender)
values('fajar', 12000, 30, 'kereta kencana','male');

drop table if exists employee;

create table employee (
    id int generated by default as identity,
    name varchar(100) not null,
    amount dec(15, 2) not null,
    division int not null,
    levels int not null,
    gender varchar(100) not null,
    account_id int not null,
    primary key(id)
);

insert into employee(name, amount, division,levels,gender,account_id)
values('agus', 10000, 1, 3,'male',1);

insert into employee(name, amount, division,levels,gender,account_id)
values('budi', 10300, 2, 5,'male',2);

insert into employee(name, amount, division,levels,gender,account_id)
values('andi', 1000, 3, 7,'male',3);

insert into employee(name, amount, division,levels,gender,account_id)
values('asep', 80000, 3, 10,'male',4);

insert into employee(name, amount, division,levels,gender,account_id)
values('rudi', 108000, 4, 12,'male',5);

insert into employee(name, amount, division,levels,gender,account_id)
values('gusti', 70000, 5, 17,'male',6);

insert into employee(name, amount, division,levels,gender,account_id)
values('asri', 80000, 3, 20,'female',7);

insert into employee(name, amount, division,levels,gender,account_id)
values('diyah', 108000, 4, 21,'female',8);

insert into employee(name, amount, division,levels,gender,account_id)
values('asha', 70000, 5, 2,'female',9);

insert into employee(name, amount, division,levels,gender,account_id)
values('bima', 208000, 5, 11,'male',12);

insert into employee(name, amount, division,levels,gender,account_id)
values('gema', 118000, 7, 32,'female',13);


select *from accounts ;


select 
accountd




